### ISSUE TITLE
'info' highlighting?

### ISSUE THREAD

**Issue by matkuki** [alemuller/tree-sitter-make#5]
Hi,

Great parser!
I have integrated it into my editor, but something seems weird, example:
![image](https://user-images.githubusercontent.com/10289651/148302038-b07d15fb-250b-4cb7-baf6-404dd56120e1.png)
In line *572*, *573* and *574*, where the `info` call ends the `#` and words up until the `$` (for example `#  Operating system:    ` in line *571*)
character are not defined, shouldn't they be text like in line *571* (purple colored)?
It seems that all `info` lines that contain `$` variables do not get their text parts parsed after the `#` character, is this intentional? Or am I perhaps doing something wrong?

Thanks,
Matic

**Comment by matkuki** [comment]
@alemuller 
Is this parser production ready?

**Comment by alemuller** [comment]
@matkuki  I made some wrong decisions when writing this parser the first time, I'm currently doing a rewrite (see rewrite branch).

Your particular example is a corner case, that, AFAIK, is not documented on the manual. There are only a few places where "#" is not a comment delimiter.

**Comment by matkuki** [comment]
Excellent, thank you for the information 👍
Looking forward to the rewrite!
