### ISSUE TITLE
String parsing mistake

### ISSUE THREAD

**Issue by matkuki** [alemuller/tree-sitter-make#9]
Hi @alemuller,

Excellent work on the rewrite 👍

There is still an issue with strings that contain $ variables. When a variable is inserted, everything after a variable is not a string anymore. For example:
![image](https://user-images.githubusercontent.com/10289651/176005442-3a2ff1c1-5667-4b24-b350-f89c65802217.png)
and:
![image](https://user-images.githubusercontent.com/10289651/176005653-3bc5ed3c-81ca-4896-b036-8deeff2b87a3.png)

Same goes for variable declaration. This is good:
![image](https://user-images.githubusercontent.com/10289651/176007344-569c6d4a-10d0-4b1f-bdd4-2c8eefcaf0db.png)
and this cancels the string:
![image](https://user-images.githubusercontent.com/10289651/176007454-9c820bba-f469-4660-acde-bdc2777569ae.png)

**Comment by matkuki** [comment]
Scratch that, I think that is my mistake in the way I parse nodes. Sorry

**Comment by alemuller** [comment]
The variables are like macros in C, ideally, they should be highlighted based on the context they are used. This feature isn't implemented in tree-sitter.
